[workspace]
members = [
	"frame/dynamic-fee",
	"frame/ethereum",
	"frame/evm",
	"frame/evm/precompile/sha3fips",
	"frame/evm/precompile/simple",
	"frame/evm/precompile/modexp",
	"frame/evm/precompile/ed25519",
	"frame/evm/precompile/bn128",
	"frame/evm/precompile/blake2",
	"frame/evm/precompile/dispatch",
	"frame/evm/precompile/curve25519",
	"client/consensus",
	"client/rpc-core",
	"client/rpc",
	"client/db",
	"client/mapping-sync",
	"primitives/consensus",
	"primitives/evm",
	"primitives/rpc",
	"template/node",
	"template/runtime",
]

# Use scale-info compatible crates that I hacked together.
[patch.crates-io]
ethereum = { git = "https://github.com/purestake/ethereum", branch = "joshy-scale-info"}

evm-core = { git = "https://github.com/purestake/evm", branch = "joshy-scale-info"}

ethereum-types = { git = "https://github.com/purestake/parity-common", branch = "joshy-scale-info-ethereum"}
rlp = { git = "https://github.com/purestake/parity-common", branch = "joshy-scale-info-ethereum"}
rlp-derive = { git = "https://github.com/purestake/parity-common", branch = "joshy-scale-info-ethereum"}
primitive-types = { git = "https://github.com/purestake/parity-common", branch = "joshy-scale-info-ethereum"}