[workspace]
members = [
	"frame/dynamic-fee",
	"frame/ethereum",
	"frame/evm",
	"frame/evm/precompile/sha3fips",
	"frame/evm/precompile/simple",
	"frame/evm/precompile/modexp",
	"frame/evm/precompile/ed25519",
	"frame/evm/precompile/bn128",
	"frame/evm/precompile/blake2",
	"frame/evm/precompile/dispatch",
	"frame/evm/precompile/curve25519",
	"client/consensus",
	"client/rpc-core",
	"client/rpc",
	"client/db",
	"client/mapping-sync",
	"primitives/consensus",
	"primitives/evm",
	"primitives/rpc",
	"template/node",
	"template/runtime",
]

# Use scale-info compatible crates that I hacked together. Each of these overrides is associated with a
# dependency in another repo
[patch.crates-io]

# RustBlockchain/evm repo: https://github.com/rust-blockchain/evm/pull/63
evm-core = { git = "https://github.com/purestake/evm", branch = "joshy-scale-info"}

# RustBlockchain/ethereum repo: https://github.com/rust-blockchain/ethereum/pull/22
ethereum = { git = "https://github.com/purestake/ethereum", branch = "joshy-scale-info"}

# Parity-common repo: https://github.com/paritytech/parity-common/pull/593
ethereum-types = { git = "https://github.com/purestake/parity-common", branch = "joshy-scale-info-ethereum"}
rlp = { git = "https://github.com/purestake/parity-common", branch = "joshy-scale-info-ethereum"}
rlp-derive = { git = "https://github.com/purestake/parity-common", branch = "joshy-scale-info-ethereum"}
primitive-types = { git = "https://github.com/purestake/parity-common", branch = "joshy-scale-info-ethereum"}