[workspace]
members = [
	"frame/dynamic-fee",
	"frame/ethereum",
	"frame/evm",
	"frame/evm/precompile/sha3fips",
	"frame/evm/precompile/simple",
	"frame/evm/precompile/modexp",
	"frame/evm/precompile/ed25519",
	"frame/evm/precompile/bn128",
	"frame/evm/precompile/blake2",
	"frame/evm/precompile/dispatch",
	"frame/evm/precompile/curve25519",
	"client/consensus",
	"client/rpc-core",
	"client/rpc",
	"client/db",
	"client/mapping-sync",
	"primitives/consensus",
	"primitives/evm",
	"primitives/rpc",
	"primitives/self-contained",
	"template/node",
	"template/runtime",
]

# These overrides are necessary to support scale-info.
# Each one is associated with a PR in a dependency repo
[patch.crates-io]

# https://github.com/rust-blockchain/evm/pull/63
evm-core = { git = "https://github.com/purestake/evm", branch = "joshy-scale-info"}

# https://github.com/rust-blockchain/ethereum/pull/22
ethereum = { git = "https://github.com/purestake/ethereum", branch = "joshy-scale-info"}
