[package]
name = "frontier-rpc-primitives"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io"]
edition = "2018"
description = "Runtime primitives for Ethereum RPC (web3) compatibility layer for Substrate."
license = "GPL-3.0"

[dependencies]
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-api = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
pallet-evm = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
ethereum = { version = "0.3", default-features = false, features = ["codec"] }
ethereum-types = { version = "0.9", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-api/std",
	"pallet-evm/std",
	"ethereum/std",
	"ethereum-types/std",
	"codec/std",
	"sp-runtime/std",
	"sp-std/std",
]
